# -*- coding: utf-8 -*-
"""Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XWdWAFw4cA8okKvsyB69qP6dVeUuNlNJ
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st
from babel.numbers import format_currency

# Set Page Title
st.set_page_config(page_title="E-Commerce Performance Dashboard", layout="wide")

# Load Data
def load_data():
    df = pd.read_csv("dashboard/main_data.csv")
    df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])
    return df

all_df = load_data()

# --- SIDEBAR ---
with st.sidebar:
    st.title("Proyek Analisis Data")
    st.image("https://github.com/dicodingacademy/assets/raw/main/logo.png")

    # Filter Rentang Waktu
    min_date = all_df["order_purchase_timestamp"].min()
    max_date = all_df["order_purchase_timestamp"].max()

    start_date, end_date = st.date_input(
        label='Rentang Waktu',
        min_value=min_date,
        max_value=max_date,
        value=[min_date, max_date]
    )

# Filter Data berdasarkan input sidebar
main_df = all_df[(all_df["order_purchase_timestamp"] >= str(start_date)) &
                 (all_df["order_purchase_timestamp"] <= str(end_date))]

# --- MAIN PAGE ---
st.header('E-Commerce Dashboard 🛍️')

# 1. Metrics Utama
col1, col2, col3 = st.columns(3)
with col1:
    total_orders = main_df.order_id.nunique()
    st.metric("Total Orders", value=total_orders)
with col2:
    total_revenue = format_currency(main_df.price.sum(), "BRL", locale='es_CO')
    st.metric("Total Revenue", value=total_revenue)
with col3:
    avg_review = round(main_df.review_score.mean(), 2)
    st.metric("Average Review Score", value=avg_review)

# 2. Visualization 1: Top Revenue Category
st.subheader("Top Revenue by Product Category")
fig, ax = plt.subplots(figsize=(16, 8))
top_revenue_df = main_df.groupby("product_category_name_english").price.sum().sort_values(ascending=False).head(10).reset_index()

sns.barplot(x="price", y="product_category_name_english", data=top_revenue_df, palette="viridis", ax=ax)
ax.set_title("10 Kategori dengan Pendapatan Tertinggi", fontsize=20)
st.pyplot(fig)

# 3. Analisis RFM (Sederhana)
st.subheader("Best Customer Based on RFM Parameters")
# ... (Masukkan kode plot RFM yang sudah kita buat sebelumnya di sini)
st.pyplot(fig_rfm)

st.caption('Copyright (c) Diko Duwi Saputra 2026')