# -*- coding: utf-8 -*-
"""Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XWdWAFw4cA8okKvsyB69qP6dVeUuNlNJ
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st
from babel.numbers import format_currency

# Set Page Title
st.set_page_config(page_title="E-Commerce Performance Dashboard", layout="wide")

# Load Data
def load_data():
    df = pd.read_csv("dashboard/main_data.csv.gz")
    df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])
    return df

all_df = load_data()

# --- SIDEBAR ---
with st.sidebar:
    st.title("Proyek Analisis Data")
    st.image("https://github.com/dicodingacademy/assets/raw/main/logo.png")

    # Filter Rentang Waktu
    min_date = all_df["order_purchase_timestamp"].min()
    max_date = all_df["order_purchase_timestamp"].max()

    start_date, end_date = st.date_input(
        label='Rentang Waktu',
        min_value=min_date,
        max_value=max_date,
        value=[min_date, max_date]
    )

# Filter Data berdasarkan input sidebar
main_df = all_df[(all_df["order_purchase_timestamp"] >= str(start_date)) &
                 (all_df["order_purchase_timestamp"] <= str(end_date))]

# --- MAIN PAGE ---
st.header('E-Commerce Dashboard 🛍️')

# 1. Metrics Utama
col1, col2, col3 = st.columns(3)
with col1:
    total_orders = main_df.order_id.nunique()
    st.metric("Total Orders", value=total_orders)
with col2:
    total_revenue = format_currency(main_df.price.sum(), "BRL", locale='es_CO')
    st.metric("Total Revenue", value=total_revenue)
with col3:
    avg_review = round(main_df.review_score.mean(), 2)
    st.metric("Average Review Score", value=avg_review)

# 2. Visualization 1: Top Revenue Category
st.subheader("Top Revenue by Product Category")
fig, ax = plt.subplots(figsize=(16, 8))
top_revenue_df = main_df.groupby("product_category_name_english").price.sum().sort_values(ascending=False).head(10).reset_index()

sns.barplot(x="price", y="product_category_name_english", data=top_revenue_df, palette="viridis", ax=ax)
ax.set_title("10 Kategori dengan Pendapatan Tertinggi", fontsize=20)
st.pyplot(fig)
# 3. Visualization 2 : Satisfication vs Sales
st.subheader("Customer Satisfaction by Product Category")
fig_sat, ax = plt.subplots(figsize=(16, 8))
# Ambil rata-rata skor review per kategori
avg_review_df = main_df.groupby("product_category_name_english").review_score.mean().sort_values(ascending=False).head(10).reset_index()

sns.barplot(x="review_score", y="product_category_name_english", data=avg_review_df, palette="rocket", ax=ax)
st.pyplot(fig_sat)
# 4. Analisis RFM (Sederhana)
recent_date = main_df['order_purchase_timestamp'].max() + pd.Timedelta(days=1)
rfm_df = main_df.groupby(by="customer_unique_id", as_index=False).agg({
    "order_purchase_timestamp": lambda x: (recent_date - x.max()).days,
    "order_id": "nunique",
    "price": "sum"
})
rfm_df.columns = ["customer_id", "recency", "frequency", "monetary"]
st.subheader("Best Customer Based on RFM Parameters")
fig_rfm, ax = plt.subplots(nrows=1, ncols=3, figsize=(30, 10)) # Ukuran disesuaikan agar rapi

colors = ["#72BCD4", "#72BCD4", "#72BCD4", "#72BCD4", "#72BCD4"]

# Visualisasi Recency
sns.barplot(y="recency", x="customer_id", data=rfm_df.sort_values(by="recency", ascending=True).head(5), palette=colors, ax=ax[0])
ax[0].set_ylabel(None)
ax[0].set_xlabel(None)
ax[0].set_title("By Recency (days)", loc="center", fontsize=18)
ax[0].tick_params(axis ='x', labelsize=12, rotation=45) # Rotation 45 biasanya sudah cukup

# Visualisasi Frequency
sns.barplot(y="frequency", x="customer_id", data=rfm_df.sort_values(by="frequency", ascending=False).head(5), palette=colors, ax=ax[1])
ax[1].set_ylabel(None)
ax[1].set_xlabel(None)
ax[1].set_title("By Frequency", loc="center", fontsize=18)
ax[1].tick_params(axis='x', labelsize=12, rotation=45)

# Visualisasi Monetary
sns.barplot(y="monetary", x="customer_id", data=rfm_df.sort_values(by="monetary", ascending=False).head(5), palette=colors, ax=ax[2])
ax[2].set_ylabel(None)
ax[2].set_xlabel(None)
ax[2].set_title("By Monetary", loc="center", fontsize=18)
ax[2].tick_params(axis='x', labelsize=12, rotation=45)
plt.suptitle("Best Customer Based on RFM Parameters (customer_id)", fontsize=25)
st.pyplot(fig_rfm)

st.caption('Copyright (c) Diko Duwi Saputra 2026')
